# Generated by Django 4.2.1 on 2023-06-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='salary',
        ),
    ]
