# Generated by Django 4.2.1 on 2023-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_internship_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
        migrations.AddField(
            model_name='internship',
            name='offer',
            field=models.TextField(default='Default offer message'),
        ),
    ]
