# Generated by Django 4.2.1 on 2023-06-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_internship_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='fullname',
            new_name='name',
        ),
    ]
