# Generated by Django 4.2.1 on 2023-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_company_name_internship_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='internship',
            name='start',
            field=models.TextField(default=''),
        ),
    ]
